FROM python:3.12-slim

RUN pip install uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync

COPY alembic/ ./alembic
COPY alembic.ini ./alembic.ini

ENV PORT=8001
EXPOSE ${PORT}

CMD ["sh", "-c", "uv run alembic upgrade head && uv run uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --reload"]
